name: Build Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt6 PyInstaller
        pip install -r requirements.txt
      
    - name: Build with PyInstaller
      run: |
        pyinstaller --name qtwebscrub --windowed --onefile main.py
        
    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-exe
        path: dist/qtwebscrub.exe

  build-macos-intel:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt6 PyInstaller
        pip install -r requirements.txt
        
    - name: Build with PyInstaller
      run: |
        pyinstaller --name qtwebscrub --windowed --onedir main.py
        
    - name: Install create-dmg
      run: |
        brew install create-dmg
        
    - name: Create DMG
      run: |
        create-dmg --volname "QTWebScrub" --window-pos 200 120 --window-size 600 300 --icon-size 100 --app-drop-link 425 120 "dist/QTWebScrub.dmg" "dist/qtwebscrub.app"
        
    - name: Upload macOS artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos-intel-dmg
        path: dist/QTWebScrub.dmg

  build-macos-arm:
    runs-on: macos-14  # macOS M1 runner
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt6 PyInstaller
        pip install -r requirements.txt
        
    - name: Build with PyInstaller
      run: |
        pyinstaller --name qtwebscrub --windowed --onedir main.py
        
    - name: Install create-dmg
      run: |
        brew install create-dmg
        
    - name: Create DMG
      run: |
        create-dmg --volname "QTWebScrub" --window-pos 200 120 --window-size 600 300 --icon-size 100 --app-drop-link 425 120 "dist/QTWebScrub.dmg" "dist/qtwebscrub.app"
        
    - name: Upload macOS artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos-arm-dmg
        path: dist/QTWebScrub.dmg

  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt6 PyInstaller
        pip install -r requirements.txt
        
    - name: Build with PyInstaller
      run: |
        pyinstaller --name qtwebscrub --windowed --onefile main.py
        
    - name: Upload Linux artifact
      uses: actions/upload-artifact@v4
      with:
        name: linux-bin
        path: dist/qtwebscrub